config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations",
        passwords: "users/passwords",
        confirmations: "users/confirmations"
  }
  resources :projects
  resources :assignments
  resources :users, only: [:show, :edit, :update]

  root 'projects#index'
  
  
  get '/projects/add_employee' => 'projects#add_employee'
  get '/projects/autofill' => 'projects#autofill'
  post '/projects/autofill' => 'projects#autofill', as: 'autofill'
  get '/autofill' => 'projects#autofill'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
    
    # where(:title, query) -> This would return an exact match of the query
    # scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
	validates :title, presence: true,
                    length: { minimum: 5 }	
    validates :company, presence: true,
                    length: { minimum: 2 }
    validates :start_date, presence: true    
    validates :end_date, presence: true
    validate :date_validation
    
    
    #validates :end_date, presence: true, date: { :after_or_equal_to => :start_date}
    
    #validates :start_date < :end_date
    
    # validate :dates

    # def self.dates
    #     if end_date && start_date
    #         errors.add(:end_date, "Start date must be before end date") if end_date < start_date
    #     end
    # end
    
    def date_validation
        if !self[:end_date].nil? && !self[:start_date].nil?
            if self[:end_date] < self[:start_date]
                errors[:end_date] << "must be after start date"
                return false
            else
                return true
            end
        
        else
            return false
        end
    end

                    
    def self.search(query)
        where("title like ? or company like ? or start_date like ? or end_date like ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%") 
    end
    
    def self.title(query)
        where("title like ?", "%#{query}%")
    end
    
    def self.company(query)
        where("company like ?", "%#{query}%")
    end
    
    def self.datestart(query)
        where("start_date='#{query}'")
    end
    
    def self.dateend(query)
        where("end_date='#{query}'")
    end
    
    has_many :assignments
    has_many :users, :through => :assignments
    accepts_nested_attributes_for :assignments
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	include ApplicationHelper
	
	
	#Function to interpret date according to a variety of common formats
	def interpretDate(dateString)
		
		begin
		
		if (dateString =~ /^\d\d?\/\d\d?\/(\d\d)$/ )
		    #puts "Format: m/d/y"
		    searchDate = Date.strptime(dateString, '%m/%d/%y')
		elsif (dateString =~ /^\d\d?\/\d\d?\/(\d\d\d\d)$/ )
		    #puts "Format: m/d/Y"
		    searchDate = Date.strptime(dateString, '%m/%d/%Y')
		elsif (dateString =~ /^\d\d?\.\d\d?\.(\d\d)$/ )
		    #puts "Format: m.d.y"
		    searchDate = Date.strptime(dateString, '%m.%d.%y')
		elsif (dateString =~ /^\d\d?\.\d\d?\.(\d\d\d\d)$/ )
		    #puts "Format: m.d.Y"
		    searchDate = Date.strptime(dateString, '%m.%d.%Y')
		elsif (dateString =~ /^\d\d?\-\d\d?\-(\d\d)$/ )
		    #puts "Format: m-d-y"
		    searchDate = Date.strptime(dateString, '%m-%d-%y')
		elsif (dateString =~ /^\d\d?\-\d\d?\-(\d\d\d\d)$/ )
		    #puts "Format: m-d-Y"
		    searchDate = Date.strptime(dateString, '%m-%d-%Y')
		else
			flash[:message] = "Unrecognized date format. Use mm.dd.yy or mm.dd.yyyy."
		    return nil
		end
		
		rescue ArgumentError => bang
			flash[:message] = "Invalid date. (Use month first, then day, then year)."
			return nil
		end
		
		
	end
	
	
	
	
	           
	def index
		@projects = Project.all
		if params[:search] && params[:search] != ""
			
			#flash[:notice] = params[:options]
    		#@projects = Project.where(params[:options] "=" params[:search] )
    		if params[:options] == "title"
    			@projects = Project.title(params[:search]).order("start_date ASC")
    		end
    		if params[:options] == "company"
    			@projects = Project.company(params[:search]).order("start_date ASC")
    		end
    		if params[:options] == "start date"
    			tempDate = interpretDate(params[:search])
    			if tempDate == nil
    				return
    			end
    			@projects = Project.datestart(tempDate.strftime("%Y-%m-%d")).order("start_date ASC")
    		end
    		if params[:options] == "end date"
    			tempDate = interpretDate(params[:search])
    			if tempDate == nil
    				return
    			end
    			@projects = Project.dateend(tempDate.strftime("%Y-%m-%d")).order("start_date ASC")
    		end
    	else
    		@projects = Project.order("start_date ASC")
	 	end
	end

	def show
		@project = Project.find(params[:id])
		@assignment = Assignment.new
		@assignments = Assignment.project(params[:id])
		#@user = User.new
		@users = User.all
	end
	
	def new
		@project = Project.new
		@projects = Project.all
		@assignment = Assignment.new
		@assignments = Assignment.project(-1)
		#@projectusers = Assignment.where(:user_id => params[:user_id])
		@users = User.all
		@user_array = []
	end
	
	def edit
		@project = Project.find(params[:id])
		@projects = Project.all
		#@projectusers = Assignment.where(:user_id => params[:user_id])
		@assignments = Assignment.project(params[:id])
		@assignment = Assignment.new
		@users = User.all
		@user_array = []
		@assignments.each do |set|
			@user_array << set.user_id
		end
		
	end
	
	
	def autofill
		#Copy info from what the user entered.
		@project.title = project_params[:title]
		@project.company = project_params[:company]
		@project.start_date = project_params[:start_date]
		@project.end_date = project_params[:end_date]
		@project.description = project_params[:description]
		@user_array = params[:assignees]
		
		if params[:duration].to_s == ""
			flash[:message] = "No duration specified."
		else
			duration = params[:duration].to_i	
			schedule_date = 0	#The to-be-scheduled start date
			
			#Copy all project start and end times to a new array
			#Only include projects with team member overlap
			sortedProjects = []
			@projects.length.times do |i|	#For each project,
				
				#Assignments for this particular project
				assignments = Assignment.project(@projects[i].id)
				
				#Enumerate the members on the project
				temp_array = []
				assignments.each_with_index do |set,i|
					temp_array << set.user_id.to_s	#Must convert to string for compatibility
				end
				
				#If members overlap with new project, consider it a conflict
				#Also only consider projcets with end dates in the future
				if temp_array && @user_array && (temp_array & @user_array).size() > 0 && @projects[i].end_date.to_date > Time.current.to_date
					sortedProjects << [@projects[i].start_date.to_date,@projects[i].end_date.to_date]
				end
				
			end
			
			#Sort array of conflicting projects by start date
			sortedProjects = sortedProjects.sort{|left,right| left[0].to_date <=> right[0].to_date}
			
			#See if new project fits before schedule
			if sortedProjects.size() > 0 && ((sortedProjects[0][0] - Time.current.to_date).to_i >= duration)
				schedule_date = Time.current.to_date
			else
				#Find where the new project fits in the schedule
				(sortedProjects.size()-1).times do |i|
					if (sortedProjects[i+1][0] - sortedProjects[i][1]).to_i >= duration
						schedule_date = sortedProjects[i][1]
						break
					end
				end
				
			end
			
			#Check if it was scheduled above
			if schedule_date == 0 && sortedProjects.size() > 0
				schedule_date = sortedProjects[sortedProjects.size()-1][1]
			elsif schedule_date == 0
				schedule_date = Time.current.to_date
			end
			
			#Set start date and end date
			@project.start_date = schedule_date
			@project.end_date = schedule_date + duration
			
		end
		
	end
	
	helper_method :autofill
	helper_method :date_validation
	
	def create	#All buttons on creation page pass through here.
		@projects = Project.all
		@users = User.all
		@assignment = Assignment.new
		@project = Project.new(project_params)
		@assignments = Assignment.project(params[:id])
		@user_array = params[:assignees]
		
		if @user_array
			flash[:message] = @user_array
		else
			@user_array = []
		end
		
		
		if params[:commit] == 'Create Project'
			#Create was pressed
			if @project.save		#Save the project
				@user_array.each do |assign|
					@assignee = Assignment.new
					@assignee.user_id = assign
					@assignee.project_id = @project.id
					@assignee.save
				end
			
				redirect_to @project
				flash[:message] = "Successfully created project"
				return
			else
				render 'new'
				return
			end
			
		elsif params[:commit] == 'Autofill'
			#Autofill was pressed
			self.autofill
			render 'new'
			return
			
		# elsif params[:commit]
		# 	flash[:message] = params[:commit]
		# 	render 'new'
		# 	return check line 121
		
		elsif params[:assign_button]

			@temp = params[:project]
			@assignment.user_id = @temp["assignment"]["user_id"]
			@assignment.project_id = @project.id
	
			if @temp && !@user_array.include?(@temp["assignment"]["user_id"]) #Need to add functionality to check if ID is present
				@user_array << @temp["assignment"]["user_id"]
				#flash[:message] = @user_array
			else
				flash[:message] = "Duplicate found"
			end
			
			render 'new'
			return
		
		elsif params[:remove_member]
		
			#Remove the member from the array
			@user_array.delete(params[:remove_member])
		
			flash[:message] ="Removed member: " + @users.find(params[:remove_member]).last_name 
			
			render 'new'
			return
			

		else
			flash[:message] = "Missed everything else"
			render 'new'
		end
		
	end
	
	def update
		@projects = Project.all
		@users = User.all
		@assignment = Assignment.new
		@assignments = Assignment.project(params[:id])
		@project = Project.find(params[:id])
		@user_array = params[:assignees]
		
		if @user_array
			flash[:message] = @user_array
		else
			@user_array = []
		end
		
		
		if params[:assign_button]
			@temp = params[:project]
			@assignment.user_id = @temp["assignment"]["user_id"]
			@assignment.project_id = @project.id
	
			if @temp && !@user_array.include?(@temp["assignment"]["user_id"]) #Need to add functionality to check if ID is present
				@user_array << @temp["assignment"]["user_id"]
				#flash[:message] = @user_array
			else
				flash[:message] = "Duplicate found"
			end
			
			render 'edit'
			return
			# if @assignment.user_id.nil? || @assignment.project_id.nil?
			# 	@project.errors.add(:select, "an employee")
			# 	render 'edit'
			# 	return
			# end
			
			# if Assignment.where(:project_id => @assignment.project_id,:user_id => @assignment.user_id).blank?
			# 	if @assignment.save
			# 		flash[:message] = "Added team member"
			# 		#flash[:ben_message] = @test["assignment"]["user_id"]
			# 	else
			# 		flash[:message] = "Error Adding Team Member"
			# 		flash[:ben_message] = @assignment.user_id
					
			# 	end
			# else
			# 	@project.errors.add(:team, "member already on team")
			# end
		elsif params[:remove_member]
		
			#Remove the member from the array
			@user_array.delete(params[:remove_member])
		
			flash[:message] ="Removed member: " + @users.find(params[:remove_member]).last_name 
			render 'edit'
			return			
		end
		
		if params[:commit] == 'Autofill'
			#Autofill was pressed
			self.autofill
			render 'edit'
		
		elsif @project.update(project_params)
				@assignments.each do |assign|
					assign.destroy
				end
				
				@user_array.each do |assign|
					@assignee = Assignment.new
					@assignee.user_id = assign
					@assignee.project_id = @project.id
					@assignee.save
				end		
			redirect_to @project
		else
			render 'edit'			
		end
	end
	
	def destroy
  		@project = Project.find(params[:id])
		@assignments = Assignment.project(params[:id])
	  	@project.destroy
	 	@assignments.each do |assign|
	 		assign.destroy
	 	end
	 
	  redirect_to projects_path
	end
	
	def search
		
	end
	
	private
		def project_params
			params.require(:project).permit(:title,:company,:start_date,:end_date,:description, project_assignments_attributes: [:id, :user_id, :assign_id])
		end
		
		def all_params
			params.permit(:title,:company,:start_date,:end_date,:description, :user_id,:duration)	
		end
		
		def assign_params
			params.permit(:proj_id, :user_id)
		end 
		
		def saved_params
			params.require(:project)
		end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_assign.html.erb
    <!--<div class="notice">Pre-Test of assignments</div>-->
   <%= f.fields_for @assignment do |assign| %>
    <div>
      <!--%= assign.label "Team Member" %>-->
      <%= assign.collection_select :user_id, @users, :id, :last_name, {:prompt   => "Select Employee"} %>
      <%= hidden_field_tag :user_id, :id %>
      <!--%= @assignment.user_id = :user_id %>-->
      
      <%= f.submit "Add Team Member", :name => 'assign_button' %>
      

    </div>
  <% end %>

app/views/projects/_assignment_fields.html.erb
<li class="control-group nested-fields">
    <div class="notice">Pre-Test of assignments</div>
  <% if @assignments %>
    <div class="notice">Test of assignments</div>
     <% @assignments.each do |assign| %>
       < "Employee" >
       <%= assign.user_id %>
     <% end %>
  <% end %>
  
  <!--<div class = "controls">-->
    <!--%= form_for @assignment do |g| %-->
    <!--  %= g.label "Employee" %>-->
    <!--  %= g.user_id %>-->
    <!--% end %>-->
  <!--</div>-->
  
  <div class = "controls">
    <!--%= f.fields_for :assignment, Assignment.new do |assignment_user %>-->
    <!--  %= assignment_user.label "Employee" %>-->
    <!--  %= assignment_user.collection_select :user_id, @users, :id, :last_name, {:prompt   => "Select a Employee"} %>-->
    <!--  %= submit_tag "Add Employee", :name => 'assign_button', class: "button button--primary" %>-->
    <!--% end %>-->
  </div>
</li>

app/views/projects/_form.html.erb
<body>
  <!--HEADER SECTION-->
  <div id="header" align = "right">
    <p>&nbsp;</p>
    <p><img src="/assets/heading.png" valign="middle" width="35%" alt=""/></p>
  </div>
  
  <!--NAVIGATION SECTION-->
  <table id="nav" width="100%" border="0">
    <tbody>
    
      <tr>
      <!--<th onClick="document.location.href='/projects/index';" scope="col" id="timelinelink" ></th>-->
      <!--<th onClick="document.location.href='/projects/new';" scope="col" id="newprojectlink"></th>-->
      <th scope="col" id="timelinelink"><%= link_to 'Timeline', projects_path(@projects)%></th>
      <th scope="col" id="newprojectlink"><%= link_to 'New Project', new_project_path(@projects)%></th>
      <% if user_signed_in? %>
        <!--Logged in as <strong>%= current_user.email %></strong>.-->
       <th scope="col" id="newprojectlink"> <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> </th>
       <th scope="col" id="newprojectlink"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></th>
      <% end %> 
      <!--<th onClick="document.location.href='theteam.html';" scope="col" id="theteamlink"></th>-->
      <!--<th onClick="document.location.href='/projects/new';" scope="col" id="logoutlink"></th>-->
      </tr>
    
    </tbody>
  </table>

  <div id="newprojectbox">
  
   <%= form_for @project, as: :project, html: { class: "edit_project", id: "form1" } do |f| %>
      <br>
      <!--% if flash[:message] %>-->
      <!--  <div class="notice">%= flash[:message] %></div>-->
      <!--% end %>-->
      <!--% if flash[:ben_message] %>-->
      <!--  <div class="notice">ben_message: %= flash[:ben_message] %></div>-->
      <!--% end %>-->
       <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
              <%= msg %>.
              <br>
            <% end %>
          </ul>
        </div>
      <% end %> 
        
        
        <% if @user_array %>
         <% @user_array.each do |user| %>
           <% if @users.exists?(:id => user) %>
            <%= hidden_field_tag 'assignees[]', user %>
           <% end %>
         <% end %>
        <% end %>
    
       <%= hidden_field_tag :duration, "10" %>
     
     <h6>NEW PROJECT</h6>
        <table align="center" width="25%" border="0">
          <tbody>
            <tr>
              <td align="left" scope="col"><%= f.label "Project" %></td>
              <td align="left" scope="col"><%= f.text_field :title %></td>
            </tr>
            <tr>
              <td align="left" scope="col"><%= f.label :company %></td>
              <td align="left" scope="col"><%= f.text_field :company %></td>
            </tr>
            <tr>  
              <td align="left" scope="col"><%= f.label :start_date %></td>
              <td align="left" scope="col"><%= f.date_field :start_date %></td>
            </tr>
            <tr>
              <td align="left" scope="col"><%= f.label :end_date %></td>
              <label for="textarea2"></label></td>
              <td align="left" scope="col"><%= f.date_field :end_date %></td>
            </tr>
            <tr>
              <td align="left" scope="col"><%= label_tag "Duration (days)"%></td>
              <td align="left" scope="col"> <%= number_field_tag :duration %></td>
              <td align="left" scope="col"> <%= f.submit 'Autofill' %></td>
            </tr>
            <tr>
              <td align="left" scope="col"><%= f.label :description %></td>
              <td align="left" scope="col"><%= f.text_area :description %></td>
            </tr>
            <tr>
              <td align="left">Team Members:</td>
              <td align="left">
                <!--% @assignments.each do |assign| %>-->
                <% if @user_array %>
                  <% for x_user in @user_array do %>
                    <label>
                      <% if @users.exists?(:id => x_user) %>
                        <%= @users.find(x_user).last_name %>
         		            <%= image_submit_tag("cancel-01.png", :name =>'remove_member', :value => x_user, width: "16px", height: "16px") %><br>
                      <% end %>
                    </label>
                  <% end %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <label for="textfield"><br>
          
        </label>
        <label for="date2">
      </label>
        <label for="textarea">
      </label>
      
      <!--<div class="field">-->
        <!--%= f.label :zedonk %><br />-->
        <!--= text_field_tag :zedonk %>-->
      <!--</div>-->
      
      <%= render partial: "assign", locals: { f: f } %>
      

      
      <!--<p>-->
        <!--%= image_submit_tag("save-01.png", width: "150px", height: "40px", :name => 'commit') %> -->
        <!--<input width="150px" height="40px" type="image" name="imageField" id="imageField" src="/assets/save-01.png">-->
      <!--</p>-->
      <p>
        <%= f.submit nil, :type => :image, :src => "/assets/save-01.png", width: "150px", height: "40px" %>
      </p>
    <% end %>
    <!--</form>-->
    

  </div>
</body>

app/views/projects/edit.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="/stylesheets/style.css">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto">
<title>Edit Project</title>

</head>

<%= render 'form' %>

<!--%= link_to 'Back', projects_path %>-->

</html>

app/views/projects/index.html.erb
<!doctype html>
<html>
  <head>
  <meta charset="utf-8">
 <!-- <%= stylesheet_link_tag "style" %>-->
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto">
  
  <title>Timeline</title>
  
  </head>
  
  
  <body>
  <!--HEADER SECTION-->
  <div id="header" align = "right">
    <p>&nbsp;</p>
    <p><img src="\assets\heading.png" valign="middle" width="35%" alt=""/></p>
  </div>
  
  <!--NAVIGATION SECTION-->
  <table id="nav" border="0">
    <tbody>
      <tr>
      <th scope="col" id="timelinelink"><%= link_to 'Timeline', projects_path(@projects)%></th>
      <th scope="col" id="newprojectlink"><%= link_to 'New Project', new_project_path(@projects)%></th>
      <% if user_signed_in? %>
        <!--Logged in as <strong>%= current_user.email %></strong>.-->
       <th scope="col" id="newprojectlink"> <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> </th>
       <th scope="col" id="newprojectlink"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></th>
      <% end %> 
    </tr>
    </tbody>
  </table>
  
  <!--TIMELINE SECTION-->
  
    <div id="overflowbox" style="border:0px ;width:100%;height:450px;">
    
      <br>
     <%= form_tag(projects_path, :method => "get", class: "search", id: "search-form") do %>
        <div class="input-append">
          <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Projects by " %> <%= select_tag :options, options_for_select(["company", "title", "start date", "end date"], params[:options]) %><button class="btn" type="submit">Search</button>
        </div><br>
      <% end %>
      </p>
      <p style="width:100%;">
        <% @projects.each do |project| %>
        <div id=company>
      	  <hr size="10px" color="#BD2F36"/>
      		<h3><%= link_to project.title, project_path(project) %></h3>
      		<h4><%= project.company %></h4>
      		<h5>Start: <%= project.start_date %><br>End: <%= project.end_date %></h5>
        </div>
        <% end %>
      </p>
    </div>
  
  </body>
</html>

app/views/projects/new.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="/stylesheets/style.css">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto">
<title>New Project</title>

</head>

<%= render 'form' %>

<!--%= link_to 'Back', projects_path %>-->

</html>

app/views/projects/show.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="/stylesheets/style.css">
<link rel="stylesheet" type="text/css" href="/stylesheets/fonts.css">
<title>New Project</title>

</head>

<body>
<!--HEADER SECTION-->
<div id="header" align = "right">
  <p>&nbsp;</p>
  <p><img src="/assets/heading.png" valign="middle" width="35%" alt=""/></p>
</div>

<!--NAVIGATION SECTION-->
<table id="nav" width="100%" border="0">
  <tbody>
    <tr>
      <th scope="col" id="timelinelink"><%= link_to 'Timeline', projects_path(@projects)%></th>
      <th scope="col" id="newprojectlink"><%= link_to 'New Project', new_project_path(@projects)%></th>
      <% if user_signed_in? %>
        <!--Logged in as <strong>%= current_user.email %></strong>.-->
       <th scope="col" id="newprojectlink"> <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> </th>
       <th scope="col" id="newprojectlink"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></th>
      <% end %> 
    </tr>
  </tbody>
</table>

<div id="newprojectbox">
  <%= form_for @project, as: :project, html: { class: "edit_project", id: "form1" } do |f| %>
     <br>
     <td><h6>VIEW PROJECT</h6></td>
        <table align="center" width="60%" border="0">
          <tbody>
            <tr>
              <td align="right" scope="col"><strong>Project:</strong> </td>
              <td align="left" scope="col"><%= @project.title %></td>
              <!--<td align="left" scope="col">Project Name:</td>-->
              <!--<td align="left" scope="col"><input name="textfield" type="text" required id="textfield" size="16px"></td>-->
            </tr>
            <tr>
              <td align="right" scope="col"><strong>Company:</strong> </td>
              <td align="left" scope="col"><%= @project.company %></td>
            </tr>
            <tr>  
              <td align="right" scope="col"><strong>Start Date:</strong> </td>
              <td align="left" scope="col"><%= @project.start_date %></td>
              <!--<td align="left"><label for="date">Start Date:</label></td>-->
              <!--<td align="left"><input name="date"  type="date" required id="date"></td>-->
            </tr>
            <tr>
              <td align="right" scope="col"><strong>End Date:</strong></td>
              <label for="textarea2"></label></td>
              <td align="left" scope="col"><%= @project.end_date %></td>
              <!--<td align="left"><label for="date3">End Date:</label>-->
              
              <!--<td align="left"><input name="date2" type="date" required id="date2"></td>-->
            </tr>
            <tr>
              <td align="right" scope="col"><strong> Description:</strong> </td>
              <td align="left" scope="col"><%= @project.description %></td>
              <!--<td align="left"><label for="textarea3">About Project:</label></td>-->
              <!--<td align="left"><textarea name="textarea" required id="textarea"></textarea></td>-->
            </tr>
            <tr>
              <td align="right"><strong>Team Members:</strong></td>
              <td align="left">
                 <% @assignments.each do |assign| %>
                <label>
                 
                  <% if @users.exists?(:id => assign.user_id) %>
                    <%= @users.find(assign.user_id).first_name %> <%= @users.find(assign.user_id).last_name %><br>
       		        <% end %>
       		        <!--%= image_submit_tag("fileclose.png", :name =>'remove_member', :value => assign.id, width: "16px", height: "16px") %><br>-->
                </label>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <label for="textfield"><br>
          
        </label>
        <label for="date2">
      </label>
        <label for="textarea">
      </label>
      
      <p>
        <%= link_to image_tag("edit-01.png", width: "150px", height: "40px", align: "center"), edit_project_path(@project) %>
      </p>
  		<p>
  		  <%= link_to image_tag("delete-01.png", width: "150px", height: "40px", align: "center"), project_path(@project),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </p>

  <% end %>
</div>
</body>
</html>

<!--%= link_to 'Back', projects_path %>-->